enable powertools in almalinux for plugin builds
irods/irods_development_environment pull request #62
Opened 2022-06-12 14:15 UTC by d-w-moore

https://github.com/irods/irods_netcdf/issues/25 is related but this requirement may apply in a broader way whenever a plugin depends on system libraries (ie build and runtime prerequisites other than irods-externals)

2022-06-13 13:48 UTC, d-w-moore commented
Yes, that would be fine.

2022-08-10 17:49 UTC, alanking commented
I think we should go ahead and combine the build steps to avoid the extra layers. @d-w-moore Then we can get this in.

2022-08-10 18:03 UTC, SwooshyCueb requested changes

2022-08-10 18:03 UTC, SwooshyCueb commented on plugin_builder.almalinux8.Dockerfile
> +    dnf config-manager --set-enabled powertools
Please collapse this into the previous `RUN` step. You can just add `dnf-plugins-core` to the package list and run `dnf config-manager --set-enabled powertools` before `dnf clean all`

2023-08-03 22:27 UTC, korydraughn commented
@d-w-moore When you find minutes, please go ahead and take care of the code review comments so we can get this merged.

2023-08-07 16:53 UTC, d-w-moore commented on plugin_builder.almalinux8.Dockerfile
> +    dnf config-manager --set-enabled powertools
Upon rebasing to tip of main, it appears:
   - I need to run
     ``` 
     --mount=type=cache,target=/var/cache/dnf,sharing=locked \
     --mount=type=cache,target=/var/cache/yum,sharing=locked \
     --mount=type=cache,target=/root/.cache/pip,sharing=locked \
     --mount=type=cache,target=/root/.cache/wheel,sharing=locked \
     ```
     on each RUN step. Correct? Not sure what those lines do....

There doesn't appear to be a `dnf clean all` line within this Dockerfile anymore, on the tip of main at least.
So then, maybe it's only important that we preserve the order of `dnf config-manager --set-enabled powertools` with respect to the install targets it affects ?

2023-08-07 16:56 UTC, SwooshyCueb commented on plugin_builder.almalinux8.Dockerfile
> +    dnf config-manager --set-enabled powertools
This bit tells buildkit to cache rpm packages between builds:
```
--mount=type=cache,target=/var/cache/dnf,sharing=locked \
--mount=type=cache,target=/var/cache/yum,sharing=locked \
```
This tells buildkit to cache python packages between builds:
```
--mount=type=cache,target=/root/.cache/pip,sharing=locked \
--mount=type=cache,target=/root/.cache/wheel,sharing=locked \
```

`dnf clean all` is no longer required as we don't want to clear our cache. (The cache won't be there in the final images; it's a mountpoint during the build process.)

2023-08-07 16:58 UTC, d-w-moore commented on plugin_builder.almalinux8.Dockerfile
> +    dnf config-manager --set-enabled powertools
Hm, new wrinkle when running that command
docker run -it almalinux:8
$ dnf install 'dnf-command(config-manager)'
$ dnf  config-manager --set-enabled powertools
Error: No matching repo to modify: powertools.

2023-08-07 16:58 UTC, SwooshyCueb commented on plugin_builder.almalinux8.Dockerfile
> +    dnf config-manager --set-enabled powertools
Either put
```
--mount=type=cache,target=/var/cache/dnf,sharing=locked \
--mount=type=cache,target=/var/cache/yum,sharing=locked \
```
or collapse it into the previous RUN statement, just after the end of the `dnf install` call

2023-08-07 21:21 UTC, SwooshyCueb commented on plugin_builder.almalinux8.Dockerfile
> +    dnf config-manager --set-enabled powertools
Add an `rm -rf /tmp/*` to this RUN statement and you should be good

2023-08-07 22:01 UTC, korydraughn reviewed
Changes look fine to me.

Don't forget to mark comments as resolved if the work has been done.

Is this ready?

2023-08-08 06:14 UTC, d-w-moore commented
> Changes look fine to me.
> 
> Don't forget to mark comments as resolved if the work has been done.
> 
> Is this ready?

I'm making sure that irods_netcdf (my current test example) builds on almalinux:8, then I'll say yes....

2023-08-08 07:17 UTC, d-w-moore commented
I've verified that this does fix the build process for `irods_netcdf`, and the tests incidentally were run again, and passed, for `4.3.0.0` of that plugin.

2023-08-08 07:18 UTC, d-w-moore commented
> I've verified that this does fix the build process for `irods_netcdf`, and the tests incidentally were run again, and passed, for `4.3.0.0` of that plugin.

Therefore I will say, @korydraughn , yes... this is ready!

2023-08-08 10:14 UTC, SwooshyCueb approved these changes

2023-08-08 11:24 UTC, korydraughn approved these changes
There's one unresolved comment left. Please mark as resolved if complete and add the pound.

2023-08-08 13:49 UTC, d-w-moore commented
> There's one unresolved comment left. Please mark as resolved if complete and add the pound.

Done! (and Done.)

2023-08-11 15:13 UTC, alanking approved these changes

2023-08-11 15:13 UTC, merged